[package]
name = "async-h1"
version = "1.1.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/async-h1"
documentation = "https://docs.rs/async-h1"
description = "Asynchronous HTTP 1.1 parser."
keywords = ["async", "http", "stream", "parser", "http1"]
categories = ["asynchronous", "parser-implementations", "web-programming", "web-programming::http-client", "web-programming::http-server"]
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"
edition = "2018"

[dependencies]
url = "2.1.0"
httparse = "1.3.3"
async-std = { version = "1.5.0", features = ["unstable"] }
http-types = { git = "https://github.com/http-rs/http-types.git", branch = "master" }
pin-project-lite = "0.1.1"
byte-pool = "0.2.1"
lazy_static = "1.4.0"
futures-core = "0.3.1"
log = "0.4"

[dev-dependencies]
pretty_assertions = "0.6.1"
async-std = { version = "1.4.0", features = ["unstable", "attributes"] }
tempfile = "3.1.0"
async-test = "1.0.0"
portpicker = "0.1.0"
